import type { GameState, RuleConfig } from '../engine'
import { KALAH_STANDARD, legalMoves } from '../engine'
import { pickMoveBeginner, pickMoveCasual, minimaxWithAB, minimaxWithABTT, ExtraTurnConfig } from './search'
import type { CancelSignal, SearchLimits, TablebaseProbe } from './search'
import { TranspositionTable } from './search'
import { evaluateStrong, evaluateExpert, WIN_SCORE, MAX_PLY } from './evaluation'
import type { BotMessage, BotWorkerMessage, BotRequest } from './types'
import { loadTablebaseFromIDB, buildProbes, TB_K, getTotalSize } from './tbStore'

export class WorkerMessageHandler {
  private currentCancel: CancelSignal | null = null
  private readonly postMsg: (msg: BotWorkerMessage) => void
  private probe: TablebaseProbe | null = null
  private tbBestMove: ((state: GameState) => number | undefined) | null = null
  private tbReady = false
  private tbLoadInFlight = false

  constructor(postMsg: (msg: BotWorkerMessage) => void) {
    this.postMsg = postMsg
    // Eagerly try to load the tablebase at worker startup.
    // The analysis worker generates and caches it in IndexedDB; the bot worker
    // never generates because a multi-second stall before the first move is
    // unacceptable.  If the table isn't cached yet the bot simply plays without
    // it and retries on the next Expert request.
    this.tryLoadTablebase()
  }

  private tryLoadTablebase(): void {
    if (this.tbReady || this.tbLoadInFlight) return
    this.tbLoadInFlight = true
    loadTablebaseFromIDB()
      .then((cached) => {
        if (cached && cached.length === getTotalSize(TB_K)) {
          const { probe, tbBestMove } = buildProbes(cached)
          this.probe = probe
          this.tbBestMove = tbBestMove
          this.tbReady = true
        }
      })
      .catch(() => {})
      .finally(() => {
        this.tbLoadInFlight = false
      })
  }

  handleMessage(msg: BotMessage): void {
    if (msg.type === 'cancel') {
      if (this.currentCancel) {
        this.currentCancel.cancelled = true
      }
      return
    }

    if (msg.type === 'pickMove') {
      // Retry tablebase load on Expert requests if not yet available.
      // The constructor already attempted; this covers the case where it
      // wasn't cached at startup but has since been generated by the analysis worker.
      if (msg.level === 'expert' && !this.tbReady) {
        this.tryLoadTablebase()
      }
      this.handlePickMove(msg)
    }
  }

  private handlePickMove(msg: BotRequest): void {
    if (this.currentCancel) {
      this.currentCancel.cancelled = true
    }

    const cancelSignal: CancelSignal = { cancelled: false }
    this.currentCancel = cancelSignal

    const { state, level, timeBudgetMs, requestId } = msg
    const rules = KALAH_STANDARD

    try {
      if (level === 'beginner') {
        const pitIndex = pickMoveBeginner(state, rules)
        this.postMsg({
          type: 'move',
          pitIndex,
          evalScore: 0,
          principalVariation: pitIndex >= 0 ? [pitIndex] : [],
          depthReached: 0,
          requestId,
        })
        this.currentCancel = null
        return
      }

      if (level === 'casual') {
        const result = pickMoveCasual(state, rules, cancelSignal)
        if (cancelSignal.cancelled) {
          this.currentCancel = null
          return
        }
        this.postMsg({
          type: 'move',
          pitIndex: result.pv[0] ?? -1,
          evalScore: result.score,
          principalVariation: result.pv,
          depthReached: 4,
          requestId,
        })
        this.currentCancel = null
        return
      }

      this.runAsyncSearch(state, level, timeBudgetMs, rules, requestId, cancelSignal)
    } catch (err) {
      this.postMsg({
        type: 'error',
        requestId,
        message: err instanceof Error ? err.message : String(err),
      })
      this.currentCancel = null
    }
  }

  private runAsyncSearch(
    state: GameState,
    level: 'strong' | 'expert',
    timeBudgetMs: number | undefined,
    rules: RuleConfig,
    requestId: number,
    cancelSignal: CancelSignal,
  ): void {
    const startTime = performance.now()
    const budget = timeBudgetMs ?? (level === 'strong' ? 1500 : 3000)
    const deadlineMs = startTime + budget
    const evalFn = level === 'strong' ? evaluateStrong : evaluateExpert
    const tt: TranspositionTable | null = level === 'expert' ? new TranspositionTable() : null

    const limits: SearchLimits = {
      deadlineMs,
      nodeCount: 0,
      aborted: false,
      checkInterval: 2048,
    }

    const killers: number[][] | undefined = tt ? [] : undefined
    const historyTable: number[][] | undefined = tt ? [new Array<number>(14).fill(0), new Array<number>(14).fill(0)] : undefined

    let bestResult = { score: 0, pv: [] as number[], depth: 0 }
    let prevRootScores: Record<number, number> | undefined
    let depth = 1

    const sendBestResult = (): void => {
      if (bestResult.pv.length === 0) {
        // If the tablebase probe fired at the root the PV is empty but we
        // have the exact score and the TB-best-move function can supply the
        // best pit.
        const tbMove = this.tbBestMove?.(state)
        if (tbMove !== undefined) {
          bestResult = {
            score: bestResult.score,
            pv: [tbMove],
            depth: bestResult.depth,
          }
        } else {
          const moves = legalMoves(state, rules)
          if (moves.length > 0) {
            bestResult = {
              score: 0,
              pv: [moves[Math.floor(Math.random() * moves.length)]!],
              depth: 0,
            }
          }
        }
      }
      this.postMsg({
        type: 'move',
        pitIndex: bestResult.pv[0] ?? -1,
        evalScore: bestResult.score,
        principalVariation: bestResult.pv,
        depthReached: bestResult.depth,
        requestId,
      })
      if (this.currentCancel === cancelSignal) {
        this.currentCancel = null
      }
    }

    const iterate = (): void => {
      if (cancelSignal.cancelled) {
        sendBestResult()
        return
      }
      if (performance.now() - startTime >= budget) {
        sendBestResult()
        return
      }

      limits.aborted = false

      const rootScores: Record<number, number> = {}

      let result: { score: number; pv: number[] }
      if (tt) {
        result = minimaxWithABTT(
          state,
          depth,
          -Infinity,
          +Infinity,
          rules,
          evalFn,
          tt,
          cancelSignal,
          rootScores,
          1,
          0,
          0,
          depth === 1 ? undefined : limits,
          ExtraTurnConfig.MAX_EXTRA_TURN_EXTENSION,
          this.probe ?? undefined,
          killers,
          historyTable,
          true,
          depth > 1 ? prevRootScores : undefined,
        )
      } else {
        result = minimaxWithAB(
          state,
          depth,
          -Infinity,
          +Infinity,
          rules,
          evalFn,
          cancelSignal,
          rootScores,
          1,
          0,
          0,
          depth === 1 ? undefined : limits,
        )
      }

      if (cancelSignal.cancelled) {
        sendBestResult()
        return
      }

      // Discard aborted mid-iteration results; keep last completed depth's result
      if (limits.aborted || isNaN(result.score)) {
        sendBestResult()
        return
      }

      bestResult = { score: result.score, pv: result.pv, depth }
      prevRootScores = rootScores

      if (bestResult.score > WIN_SCORE - MAX_PLY) {
        sendBestResult()
        return
      }

      depth++
      setTimeout(iterate, 0)
    }

    setTimeout(iterate, 0)
  }
}

// Self-hosted worker entry
if (typeof self !== 'undefined' && typeof self.postMessage === 'function') {
  const handler = new WorkerMessageHandler((msg) => self.postMessage(msg))
  self.onmessage = (event: MessageEvent<BotMessage>) => {
    handler.handleMessage(event.data)
  }
}
