export const strings = {
  appTitle: 'Mancala',
  nav: {
    play: 'Play',
    home: 'Home',
    history: 'History',
    stats: 'Stats',
    settings: 'Settings',
    back: 'Back',
  },
  home: {
    playVsBot: 'Play vs Bot',
    playVsBotDesc: 'Challenge the AI at your chosen level',
    local2Player: 'Local 2-Player',
    local2PlayerDesc: 'Pass-and-play with a friend',
    gameHistory: 'Game History',
    settings: 'Settings',
    resumeGame: 'Resume Game',
    resumePlaying: 'Continue playing',
    resumeFinished: 'Game over \u2014 review',
    statistics: 'Statistics',
    bestMoves: 'Best Moves',
    noGames: 'No games yet',
  },
  botSelect: {
    title: 'Bot Setup',
    level: 'Bot Level',
    beginner: 'Beginner',
    casual: 'Casual',
    strong: 'Strong',
    expert: 'Expert',
    side: 'Your Side',
    top: 'Top',
    bottom: 'Bottom',
    random: 'Random',
    startGame: 'Start Game',
  },
  game: {
    you: 'You',
    bot: 'Bot',
    player1: 'Player 1',
    player2: 'Player 2',
    thinking: 'Bot is thinking\u2026',
    yourTurn: 'Your turn',
    passTo: 'Pass to',
    newGame: 'New Game',
    reviewGame: 'Review Game',
    home: 'Home',
    takeback: 'Take Back',
    gameOver: 'Game Over!',
    draw: "It's a draw!",
    winner: (name: string) => `${name} wins!`,
    score: (score: number) => `${score}`,
    showCounts: 'Show counts',
    hideCounts: 'Hide counts',
    hint: 'Hint',
    liveAnalysisOn: 'Live analysis ON',
    shareGame: 'Share Game',
    shareCopied: 'Link copied!',
    shareFailed: 'Sharing failed',
    playFromHere: 'Play from this position',
  },
  settings: {
    title: 'Settings',
    theme: 'Theme',
    warmEarth: 'Warm Earth',
    darkMuseum: 'Dark Museum',
    modernDesert: 'Modern Desert',
    sound: 'Sound',
    haptics: 'Haptics',
    animationSpeed: 'Animation Speed',
    liveHints: 'Live Hints',
    liveHintsDesc: 'Show evaluation and best move during play',
    replayTutorial: 'Replay Tutorial',
    resetAll: 'Reset All Settings',
    showPitCounts: 'Show Pit Counts',
    showPitCountsDesc: 'Display numbers next to pits',
  },
  review: {
    title: 'Review',
    analyzing: 'Analyzing\u2026',
    preparingEndgameTables: 'Preparing endgame tables\u2026',
    progress: (current: number, total: number) => `${current} / ${total}`,
    evalGraph: 'Evaluation',
    moveList: 'Moves',
    best: 'Best',
    excellent: 'Excellent',
    good: 'Good',
    inaccuracy: 'Inaccuracy',
    mistake: 'Mistake',
    blunder: 'Blunder',
    seeWhatHappened: 'See what should have happened',
    linePlaysToEnd: 'Line plays to the end of the game',
    recommended: 'Recommended',
    played: 'Played',
    stones: (n: number) => `${n >= 0 ? '+' : ''}${n.toFixed(1)}`,
    backToGame: 'Back to game',
    noPV: 'No variation available',
    play: 'Play',
    pause: 'Pause',
    shareGame: 'Share Game',
  },
  history: {
    title: 'Game History',
    empty: 'No games yet. Play a game to see it here!',
    delete: 'Delete',
    deleteConfirm: 'Delete this game record?',
    clearAll: 'Clear All',
    clearConfirm: 'Are you sure? This will permanently delete all game history.',
    vs: 'vs',
    win: 'W',
    loss: 'L',
    draw: 'D',
    filterAll: 'All',
    filterBot: 'Bot',
    filterLocal: 'Local',
    noMatchFilter: 'No games match the selected filters.',
    playFirstGame: 'Play your first game',
    totalGames: 'Total Games',
    winRate: 'Win Rate',
    streak: 'Streak',
    replay: 'Replay',
    bestMoves: 'Best Moves',
    accuracy: 'Accuracy',
  },
  stats: {
    title: 'Statistics',
    totalGames: 'Total Games',
    wins: 'Wins',
    losses: 'Losses',
    draws: 'Draws',
    winRate: 'Win Rate',
    byBotLevel: 'By Bot Level',
    classificationDist: 'Move Classification Distribution',
    noAnalysisData: 'No analysis data yet. Review games to populate.',
    blundersOverTime: 'Blunders per Game',
    refresh: 'Refresh Stats',
    empty: 'No games yet. Play some games to see statistics!',
    accuracyOverTime: 'Best Move % per Game',
    avgAccuracy: 'Avg Best Move',
    avgGameLength: 'Avg Game Length',
    accuracy: 'Accuracy',
    needMoreGames: 'Need at least 2 analyzed games for a trend chart.',
    noBotGames: 'No bot games played.',
  },
  tutorial: {
    title: 'How to Play Mancala',
    next: 'Next',
    prev: 'Back',
    done: 'Got it!',
    skip: 'Skip tutorial',
    panels: [
      {
        title: 'The Board & Your Goal',
        text: 'The board has 12 pits (6 per side) and 2 large stores. Each pit starts with 4 stones. Your goal is to collect more stones in your store than your opponent.',
      },
      {
        title: 'Sowing Stones',
        text: "Pick a pit on your side. All its stones are picked up and sown one-by-one counterclockwise into the following pits. Skip your opponent's store — only your own store collects during sowing.",
      },
      {
        title: 'Extra Turn',
        text: 'If the last stone lands in your own store, you get an extra turn! This is a key strategic element — chain multiple moves together.',
      },
      {
        title: 'Captures',
        text: "If the last stone lands in an empty pit on your side, you capture that stone plus all stones in the pit directly opposite on the opponent's side. They go into your store.",
      },
      {
        title: 'Game End',
        text: "The game ends when one player's side is completely empty. The opponent collects all remaining stones from their side into their store. The player with the most stones wins.",
      },
      {
        title: 'Pro Tip',
        text: 'Look ahead 1-2 moves. Watch for setups where you can end in an empty pit to capture. Ending in your store for extra turns lets you chain moves and control the tempo.',
      },
    ] as { title: string; text: string }[],
  },
  placeholder: {
    gameHistory: 'Game history coming soon.',
    analysis: 'Analysis coming soon.',
  },
  shared: {
    readOnlyReview: 'Shared Game Review',
    playFromHere: 'Play from this position',
    startNewGame: 'Start new game',
  },
} as const
