export const strings = {
  appTitle: 'Mancala',
  home: {
    playVsBot: 'Play vs Bot',
    local2Player: 'Local 2-Player',
    gameHistory: 'Game History',
    settings: 'Settings',
    resumeGame: 'Resume Game',
  },
  botSelect: {
    title: 'Bot Setup',
    level: 'Bot Level',
    beginner: 'Beginner',
    casual: 'Casual',
    strong: 'Strong',
    expert: 'Expert',
    side: 'Your Side',
    top: 'Top',
    bottom: 'Bottom',
    random: 'Random',
    startGame: 'Start Game',
  },
  game: {
    you: 'You',
    bot: 'Bot',
    player1: 'Player 1',
    player2: 'Player 2',
    thinking: 'Bot is thinking\u2026',
    yourTurn: 'Your turn',
    passTo: 'Pass to',
    newGame: 'New Game',
    reviewGame: 'Review Game',
    home: 'Home',
    takeback: 'Take Back',
    gameOver: 'Game Over!',
    draw: "It's a draw!",
    winner: (name: string) => `${name} wins!`,
    score: (score: number) => `${score}`,
    showCounts: 'Show counts',
    hideCounts: 'Hide counts',
    hint: 'Hint',
    liveAnalysisOn: 'Live analysis ON',
  },
  settings: {
    title: 'Settings',
    theme: 'Theme',
    warmEarth: 'Warm Earth',
    darkMuseum: 'Dark Museum',
    modernDesert: 'Modern Desert',
    boardFlip: 'Board Flip',
    boardFlipDesc: 'Rotate board for each player',
    sound: 'Sound',
    haptics: 'Haptics',
    animationSpeed: 'Animation Speed',
    liveHints: 'Live Hints',
    liveHintsDesc: 'Show evaluation and best move during play',
    replayTutorial: 'Replay Tutorial',
    resetAll: 'Reset All Settings',
    stonePattern: 'Stone Pattern',
    stonePatternRandom: 'Random',
    stonePatternSymmetric: 'Symmetric',
    showPitCounts: 'Show Pit Counts',
    showPitCountsDesc: 'Display numbers next to pits',
  },
  review: {
    title: 'Review',
    analyzing: 'Analyzing\u2026',
    progress: (current: number, total: number) => `${current} / ${total}`,
    evalGraph: 'Evaluation',
    moveList: 'Moves',
    best: 'Best',
    excellent: 'Excellent',
    good: 'Good',
    inaccuracy: 'Inaccuracy',
    mistake: 'Mistake',
    blunder: 'Blunder',
    seeWhatHappened: 'See what should have happened',
    recommended: 'Recommended',
    played: 'Played',
    stones: (n: number) => `${n >= 0 ? '+' : ''}${n.toFixed(1)}`,
    backToGame: 'Back to game',
    noPV: 'No variation available',
  },
  placeholder: {
    gameHistory: 'Game history coming soon.',
    analysis: 'Analysis coming soon.',
  },
} as const
