export const strings = {
  appTitle: 'Mancala',
  home: {
    playVsBot: 'Play vs Bot',
    local2Player: 'Local 2-Player',
    gameHistory: 'Game History',
    settings: 'Settings',
    resumeGame: 'Resume Game',
  },
  botSelect: {
    title: 'Bot Setup',
    level: 'Bot Level',
    beginner: 'Beginner',
    casual: 'Casual',
    strong: 'Strong',
    expert: 'Expert',
    side: 'Your Side',
    top: 'Top',
    bottom: 'Bottom',
    random: 'Random',
    startGame: 'Start Game',
  },
  game: {
    you: 'You',
    bot: 'Bot',
    player1: 'Player 1',
    player2: 'Player 2',
    thinking: 'Bot is thinking\u2026',
    yourTurn: 'Your turn',
    passTo: 'Pass to',
    newGame: 'New Game',
    reviewGame: 'Review Game',
    home: 'Home',
    takeback: 'Take Back',
    gameOver: 'Game Over!',
    draw: "It's a draw!",
    winner: (name: string) => `${name} wins!`,
    score: (score: number) => `${score}`,
  },
  settings: {
    title: 'Settings',
    theme: 'Theme',
    warmEarth: 'Warm Earth',
    darkMuseum: 'Dark Museum',
    modernDesert: 'Modern Desert',
    boardFlip: 'Board Flip',
    boardFlipDesc: 'Rotate board for each player',
    sound: 'Sound',
    haptics: 'Haptics',
    animationSpeed: 'Animation Speed',
    liveHints: 'Live Hints',
    replayTutorial: 'Replay Tutorial',
    resetAll: 'Reset All Settings',
  },
  placeholder: {
    gameHistory: 'Game history coming soon.',
    analysis: 'Analysis coming soon.',
  },
} as const
